// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4S4LnOWwNfu45DKgDxBLO-OpUm7j4Sag',
    appId: '1:800249476068:web:589db2139ddb8c1bfdcdf1',
    messagingSenderId: '800249476068',
    projectId: 'keyboard-5b001',
    authDomain: 'keyboard-5b001.firebaseapp.com',
    storageBucket: 'keyboard-5b001.appspot.com',
    measurementId: 'G-ZF7EGPBPSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4qxtzdK6wMqLdzBvQtJpNpyPZTD5hOiU',
    appId: '1:800249476068:android:b65e0c5a1f93c1e0fdcdf1',
    messagingSenderId: '800249476068',
    projectId: 'keyboard-5b001',
    storageBucket: 'keyboard-5b001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9wTRB3gJPWaRzJvhug-bMsAFIZMLG7fE',
    appId: '1:800249476068:ios:814061e6f83e72d6fdcdf1',
    messagingSenderId: '800249476068',
    projectId: 'keyboard-5b001',
    storageBucket: 'keyboard-5b001.appspot.com',
    iosClientId: '800249476068-097hn825f1u7p3gtquluvjm0kkqbdu91.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9wTRB3gJPWaRzJvhug-bMsAFIZMLG7fE',
    appId: '1:800249476068:ios:814061e6f83e72d6fdcdf1',
    messagingSenderId: '800249476068',
    projectId: 'keyboard-5b001',
    storageBucket: 'keyboard-5b001.appspot.com',
    iosClientId: '800249476068-097hn825f1u7p3gtquluvjm0kkqbdu91.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );
}
